Fix unable to generate keys error
bcgov/api-services-portal pull request #1028
Opened 2024-04-03 22:29 UTC by Elson9

2024-04-04 17:53 UTC, rustyjux approved these changes
I successfully created a credential (w/ Kong API key) on the feature deployment. 

I am curious to see the consumer details being passed through to Grafana but not sure if that works for feature deployments (since I was logging into the Portal w/ janis@idir).

2024-04-10 22:28 UTC, ikethecoder requested changes

2024-04-10 22:28 UTC, ikethecoder commented on src/services/kong/consumer-service.ts
> +          .replace(/[^A-Za-z0-9:-]/gim, '')
I think this regexp replace should be pulled out into a function that you can have a unit test for, to confirm that it is going to produce the expected output.  And it will also avoid having the logic duplicated.

2024-04-11 16:05 UTC, ikethecoder approved these changes

2024-04-11 17:28 UTC, merged