Feature/ns to gw portal labels
bcgov/api-services-portal pull request #1077
Opened 2024-06-27 22:29 UTC by rustyjux

Closes #1067

2024-07-03 17:15 UTC, Elson9 approved these changes

2024-07-03 23:15 UTC, ikethecoder requested changes

2024-07-03 23:15 UTC, ikethecoder commented on src/nextapp/components/new-namespace/new-namespace.tsx
> +              <FormLabel>Gateway Name</FormLabel>
Should probably either delete this `new-namespace` component all together, or update the label to represent "Gateway ID"

2024-07-03 23:15 UTC, ikethecoder commented on src/nextapp/components/service-accounts-list/service-accounts-list.tsx
> +  console.log('list',list)
can remove

2024-07-03 23:15 UTC, ikethecoder commented on src/nextapp/pages/manager/gateways/detail.tsx
> +          title: ' Gateway deleted',
I don't think there needs to be a space in front - think it was there before mistakenly

2024-07-04 16:25 UTC, rustyjux commented on src/nextapp/components/new-namespace/new-namespace.tsx
> +              <FormLabel>Gateway Name</FormLabel>
while we aren't using it, let's leave it for now in case we backpedal

2024-07-04 16:27 UTC, rustyjux commented on src/nextapp/pages/manager/gateways/detail.tsx
> +          title: ' Gateway deleted',
That's what I thought but it's repeated in a couple places and looks nice with the space, but I didn't check appearance w/o the space. I'll have a peek

2024-07-05 15:56 UTC, merged