Fix to add Rate Limit Plugin with Redis Policy
bcgov/api-services-portal pull request #163
Opened 2021-08-04 16:22 UTC by NithinKuruba

Fixes #104

2021-08-04 17:21 UTC, ikethecoder requested changes

2021-08-04 17:21 UTC, ikethecoder commented on src/services/kong/consumer-service.ts
> +  private gwaUrl: string = process.env.GWA_API_URL;
Can you make consistent the setting of the values for`kongUrl` and `gwaUrl`?  They both are set from environment variables.  I prefer constructor injection, but either way, approach should be same.

2021-08-04 18:04 UTC, NithinKuruba commented on src/services/kong/consumer-service.ts
> +  private gwaUrl: string = process.env.GWA_API_URL;
@ikethecoder Yup, I like the idea of constructor injection. Made the changes.

2021-08-06 03:44 UTC, ikethecoder approved these changes

2021-08-06 03:47 UTC, merged