Niraj local  1
bcgov/api-services-portal pull request #272
Opened 2021-12-14 20:15 UTC by nirajCITZ

1)Make changes to make the script executable without cookie issue (Zenhub ticket # 255)
2)Added verification step to check that the API is accessible with the API key once the access request is granted

2021-12-14 21:44 UTC, NithinKuruba commented on e2e/cypress/support/auth-commands.ts
> +Cypress.Commands.add('getAPIRequest', (serviceName : string) => {
I recommend using a different name as `getAPIRequest` would not convey the right info about what it actually does. Infact, you can create a command that can handle all the requests like GET, POST/PUT and DELETE, could be used in upcoming tests. Probably call this function `makeKongRequest`?

2021-12-14 22:05 UTC, NithinKuruba commented on e2e/cypress/support/auth-commands.ts
> +Cypress.Commands.add('deleteAllCookies', () => {
@nirajCITZ we had a custom command `removeCookies`. so if its not being used anywhere, please feel free to remove it as it would be good to have just one function to clear the cookies.

2021-12-14 22:07 UTC, NithinKuruba requested changes
@nirajCITZ I have added couple of comments for changes.

2021-12-15 22:01 UTC, nirajCITZ commented on e2e/cypress/support/auth-commands.ts
> +Cypress.Commands.add('getAPIRequest', (serviceName : string) => {
Done

2021-12-15 22:01 UTC, nirajCITZ commented on e2e/cypress/support/auth-commands.ts
> +Cypress.Commands.add('deleteAllCookies', () => {
Done

2021-12-15 22:28 UTC, NithinKuruba commented on e2e/cypress/support/auth-commands.ts
> +Cypress.Commands.add('makeKongRequest', (serviceName : string, methodType : string) => {
@nirajCITZ thanks for updating this function. The function need to accept headers and payload as well to make it work for POST/PUT requests. The headers may be added and updated depending upon different scenarios.

2021-12-16 02:50 UTC, nirajCITZ commented on e2e/cypress/support/auth-commands.ts
> +Cypress.Commands.add('makeKongRequest', (serviceName : string, methodType : string) => {
As discussed, we will keep optimizing it as we come across with different scenarios

2021-12-16 18:37 UTC, NithinKuruba approved these changes

2021-12-16 18:37 UTC, merged