Merging test automation branch into dev to avoid future conflicts
bcgov/api-services-portal pull request #287
Opened 2022-01-14 18:56 UTC by NithinKuruba

2022-01-19 22:32 UTC, Jonesy commented on e2e/cypress/support/auth-commands.ts
> +  debugger
Should this stray debugger be removed?

2022-01-20 19:53 UTC, NithinKuruba commented on e2e/cypress/support/auth-commands.ts
> +  debugger
Removed

2022-01-20 19:54 UTC, NithinKuruba commented on src/nextapp/components/forms/list-input.tsx
> +  dataTestId?: string;
yep should be good idea.

2022-01-20 19:54 UTC, NithinKuruba commented on src/nextapp/pages/devportal/requests/new/[id].tsx
> +                        data-testid={'access-rqst-app-env-' + e.name}
done

2022-01-20 19:54 UTC, NithinKuruba commented on src/nextapp/components/products-list/add-environment.tsx
> +      <MenuButton as={Button} variant="unstyled" data-testid={productName.toLowerCase().replaceAll(' ', '-') + "-add-env-btn"}>
done

2022-01-20 20:02 UTC, Jonesy requested changes

2022-01-20 20:02 UTC, Jonesy commented on src/nextapp/components/products-list/add-environment.tsx
> +              data-testid={kebabCase(productName) + `-prd-env-item-${e.value}`}
Prefer ```data-testid={`${kebabCase(productName)}-prd-env-item-${e.value}`}``` for consistency

2022-01-20 20:02 UTC, Jonesy commented on src/nextapp/components/products-list/add-environment.tsx
> +import { kebabCase } from 'lodash';
See first comment for correct import declaration

2022-01-20 20:02 UTC, Jonesy commented on src/nextapp/components/environments-list/environments-list.tsx
> +                  data-testid={kebabCase(product.name) + `-${e.name}-edit-btn`}
Duplicate of earlier revision request

2022-01-21 17:54 UTC, Jonesy approved these changes

2022-01-21 19:07 UTC, merged