Add footer pages
bcgov/api-services-portal pull request #617
Opened 2022-10-25 23:47 UTC by jTendeck

2022-10-26 03:40 UTC, Jonesy requested changes
Use Next.js' Markdown support to render Markdown files instead of parsing strings inside React components.

2022-10-26 03:40 UTC, Jonesy commented on src/nextapp/pages/content/about-us.tsx
> +  let pageHeader = 'About Us';
Use `const` over `let` if you are not going to mutate this value. I generally just write string props directly on the component.

2022-10-26 03:40 UTC, Jonesy commented on src/nextapp/components/footer-page/footer-page.tsx
> +const FooterPage: React.FC<FooterPageProps> = (props) => {
Prefer the convention of destructuring prop arguments instead of a single `prop` argument. ie `const Component = ({ pageHeader, updateDate, content }) =>`

2022-10-26 03:40 UTC, Jonesy commented on src/nextapp/components/footer-page/footer-page.tsx
> +const FooterPage: React.FC<FooterPageProps> = (props) => {
Generally try to stay away from super specific names like `FooterPage` for a layout that likely could be used for pages not coming from the Footer. Something like `ContentPage` would work better.

2022-11-01 22:23 UTC, Jonesy requested changes

2022-11-01 22:23 UTC, Jonesy commented on src/nextapp/pages/_app.tsx
> +                          <Box
One adjustment here, generally I prefer to import the UI kit's `Link` component and bring in Next's link as `NextLink`. Then structure the links like this

```tsx
<NextLink passHref href={f.href}>
  <Link fontSize="xs" px="5px" py={...}>
    {f.text}
  </Link>
</NextLink>
```
The reason is because Next Links aren't anchor tags by default, so we loose some accessibility for free, as well as semantic CSS. The Chakra `Link` component also gives us normal link CSS behaviour for free, so we don't have to add other classes like `cursor`, `display`, etc to mimic the standard behaviour.

2022-11-01 23:23 UTC, jTendeck commented on src/nextapp/pages/_app.tsx
> +                          <Box
Ahh, thanks for the feedback and info Josh... I've implemented your feedback :)

2022-11-02 16:38 UTC, Jonesy approved these changes

2022-11-02 18:18 UTC, merged