fixes request access button not being displayed when the Product has …
bcgov/api-services-portal pull request #879
Opened 2023-08-17 16:08 UTC by Elson9

…an inactive environment

Fixes #631

2023-08-17 19:49 UTC, Jonesy requested changes

2023-08-17 19:49 UTC, Jonesy commented on src/nextapp/components/api-product-item/api-product-item.tsx
>              {isPublic && (
Because you're rendering the same form component and props I think you can just render this component alone in the `!isTiered` check, it's the same as showing it if `isPublic` was true or false.

2023-08-21 23:12 UTC, Elson9 commented on src/nextapp/components/api-product-item/api-product-item.tsx
>              {isPublic && (
Thanks Josh, I had left that in originally in case there's a future need for that logic, but I guess we can just add it in if/when necessary.

2023-09-07 09:33 UTC, ikethecoder approved these changes

2023-09-07 09:33 UTC, merged