Cypress gwa cli
bcgov/api-services-portal pull request #896
Opened 2023-09-06 16:19 UTC by nirajCITZ

1)Added/Updated scenarios for GWA CLI
2)Uddate github action workflow
3)Added scenarios for zenhub#889 and 887

2023-09-11 21:33 UTC, Jonesy requested changes

2023-09-11 21:33 UTC, Jonesy commented on .github/workflows/aps-cypress-e2e.yaml
> +          go-version: '1.19.x'
I can't recall if this added bugs or not but you might want to set it to run at Go 1.20, which is the same version as the CLI's codebase.

2023-09-11 21:33 UTC, Jonesy commented on .github/workflows/build-gwa-binary.yaml
> +          go-version: 1.16 # Replace with the desired Go version
Same here, this might cause some issues.

2023-09-11 21:33 UTC, Jonesy commented on e2e/cypress/support/auth-commands.ts
> +                  debugger
Stray debugger

2023-09-11 21:33 UTC, Jonesy commented on e2e/cypress/support/util-commands.ts
>  import jsonpath = require('jsonpath');
This might cause you some issues, should either `import jsonpath from 'jsonpath'` or `const jsonpath = require('jsonpath');`.

2023-09-11 21:33 UTC, Jonesy commented on e2e/cypress/tests/01-api-key/09-gwa-get.ts
> +        debugger
stray debugger

2023-09-11 21:33 UTC, Jonesy commented on e2e/cypress/tests/15-aps-api/05-authorizationProfiles.cy.ts
> +            debugger
Stray debugger

2023-09-11 21:33 UTC, Jonesy commented on e2e/cypress/tests/16-gwa-cli/02-cli-generate-config.ts
> +      debugger
debugger

2023-09-13 21:37 UTC, ikethecoder commented on .github/workflows/aps-cypress-e2e.yaml
> +          git clone https://github.com/bcgov/gwa-cli.git -b dev
Don't specify "dev" because we are probably going to remove "dev" and change "master" to "main".. so better just to leave `-b dev` off and use default.

2023-09-15 17:45 UTC, Jonesy approved these changes

2023-09-15 17:48 UTC, ikethecoder approved these changes

2023-09-15 17:49 UTC, merged