sprint 82 fixes
bcgov/api-services-portal pull request #943
Opened 2023-10-24 17:19 UTC by ikethecoder

2023-10-26 04:54 UTC, ikethecoder commented
@nirajCITZ When you have some time, go at it for retesting these defects :)

2023-10-27 21:43 UTC, jTendeck approved these changes

2023-10-30 18:12 UTC, Jonesy requested changes
Just some minor changes, the error assignment one is optional, but with the operators there's a potential for some values to slip by.

2023-10-30 18:12 UTC, Jonesy commented on src/services/notification/notification.service.ts
> +    const name = (to.name == '' ? null : to.name) ?? 'Portal User';
To be safe I would just change this ternary to `!to.name ? 'Portal User' : to.name`

2023-10-30 18:12 UTC, Jonesy commented on src/services/checkStatus.ts
>        error['reason'] = errors['error'];
You could just write `error.reason`, just a little less typing :), also if it's available you could go like this:

```typescript
error.reason = errors?.error ?? '';
```
if you wanted a default string there.

2023-10-30 18:12 UTC, Jonesy commented on src/nextapp/components/service-routes/service-routes.tsx
> +      if (paths.length == 0) {
To be safe I'd just add a triple `===`

2023-10-30 18:12 UTC, Jonesy commented on src/nextapp/components/api-product-item/api-product-item.tsx
> +  const isProtected = data.environments.some((e) => e.flow != 'public');
Add an extra `=` to the `!==` because JavaScript :P

2023-10-30 18:12 UTC, Jonesy commented on src/batch/feed-worker.ts
> +  if (result.status != 200) {
Add a `!==` for safety

2023-11-01 20:38 UTC, ikethecoder commented on src/services/notification/notification.service.ts
> +    const name = (to.name == '' ? null : to.name) ?? 'Portal User';
@Jonesy if the name is blank ("") I want it to display "Portal User".. the one you suggest does not do this.

2023-11-01 20:49 UTC, ikethecoder commented on src/services/notification/notification.service.ts
> +    const name = (to.name == '' ? null : to.name) ?? 'Portal User';
I went with using: `const isEmpty = (str: string) => !str?.length;`

2023-11-01 23:47 UTC, Elson9 approved these changes

2023-11-02 01:03 UTC, merged